server:
  port: 9000 #服务端口
spring:
  application:
    name: zuul-gateway #指定服务名
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
zuul:
  routes: #定义服务转发规则
    ribbon-consumer: #名字尽量和业务系统相关
      path: /consumer-zuul/** #匹配consumer-zuul的请求consumer服务
      serviceid: ribbon-consumer
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
## 设置ribbon的hystrix的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000